name: Upload Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - "**"

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the push has a tag
        run: |
          if [ -z "$(git describe --tags --exact-match 2>/dev/null)" ] && [ "${GITHUB_REF_NAME}" == "main" ]; then
            echo "Push to 'main' is forbidden without a tag."
            exit 1
          fi
    
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Set PACKAGE_VERSION
        run: |
          # 获取最新的标签
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          
          # 检查当前分支
          if [ "${GITHUB_REF_NAME}" == "main" ]; then
            # 主分支使用标签版本
            PACKAGE_VERSION=$LATEST_TAG
          else
            # 非主分支，生成开发版本号
            BRANCH_NAME=$(echo "${GITHUB_REF_NAME}" | sed 's|/|_|g')  # 替换非法字符
            BRANCH_CLEAN=$(echo "$BRANCH_NAME" | sed 's/[^a-zA-Z0-9]/_/g')  # 去除特殊字符
            COMMIT_SHA=$(git rev-parse --short HEAD)  # 获取当前提交的短 SHA
            PACKAGE_VERSION="${LATEST_TAG}.dev+${COMMIT_SHA}"
          fi

          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "Generated PACKAGE_VERSION=${PACKAGE_VERSION}"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build

      - name: Debug dist folder
        run: ls -la dist/

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/
      
  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Debug retrieved artifact
        run: ls -la dist/

     
