name: Upload Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the push has a tag
        if: ${{ github.ref_name == 'main' }}
        run: |
          if [ -z "$(git describe --tags --exact-match 2>/dev/null)" ]; then
            echo "Push to 'main' is forbidden without a tag."
            exit 1
          fi

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # 确保完整历史

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Set PACKAGE_VERSION
        run: |
          MAIN_LATEST_TAG=$(git describe --tags --abbrev=0 main 2>/dev/null || echo "0.0.0")

          if [ "${GITHUB_REF_NAME}" == "main" ]; then
            PACKAGE_VERSION=${GITHUB_REF_NAME}
          else
            TIMESTAMP=$(TZ=UTC date +%Y%m%d%H%M%S)
            PACKAGE_VERSION="${MAIN_LATEST_TAG}.dev${TIMESTAMP}"
          fi
          
          echo "PACKAGE_VERSION=${PACKAGE_VERSION}" >> $GITHUB_ENV
          echo "Generated PACKAGE_VERSION=${PACKAGE_VERSION}"

      - name: Build release distributions
        run: |
          python -m pip install build
          python -m build
      
      - name: Debug dist folder
        run: |
          echo "Contents of dist/:"
          ls -la dist/

      - name: Upload distributions
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: dist/

  pypi-publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write

    environment:
      name: pypi

    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: dist/

      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
