name: Upload Python Package

on:
  release:
    types: [published]
  push:
    branches:
      - main
      - "**"

permissions:
  contents: read

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the push has a tag
        run: |
          if [ -z "$(git describe --tags --exact-match 2>/dev/null)" ] && [ "${GITHUB_REF_NAME}" == "main" ]; then
            echo "Push to 'main' is forbidden without a tag."
            exit 1
          fi

      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip setuptools wheel

      - name: Set PACKAGE_VERSION
        run: |
          LATEST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "0.0.0")
          
          if [ "${GITHUB_REF_NAME}" == "main" ]; then
            if [ -z "$(git describe --tags --exact-match 2>/dev/null)" ]; then
              PACKAGE_VERSION="0.0.0.dev$(TZ=UTC date +%Y%m%d%H%M%S)"
            else
              PACKAGE_VERSION=$LATEST_TAG
            fi
          else
            BRANCH_NAME=$(echo "${GITHUB
